### ISSUE TITLE
Magento 2.3.3 community - compile error

### ISSUE THREAD

**Issue by an4rei** [mageplaza/magento-2-social-login#155]
### Preconditions

1. Magento: 2.3.3
2. PHP: 7.2
3. MySQL: mariadb

### Steps to reproduce

1. bin/magento setup:upgrade after composer finishes updating to magento 2.3.3 from 2.3.2
2. bin/magento setup:di:compile

### Expected result

1. finish di:compilation successfully 

### Actual result

1. 
```
Compilation was started.
Interception cache generation... 6/7 [========================>---]  85% 39 secs 431.0 MiBErrors during compilation:
        Mageplaza\SocialLogin\Controller\Popup\Create
                Missed required argument customerRepository in parent::__construct call. File: vendor/mageplaza/magento-2-social-login/Controller/Popup/Create.php
Total Errors Count: 1
```

**Comment by volanar** [comment]
This error occurred to me. Incompatibility with magento 2.3.3

**Comment by Victor-Mageplaza** [comment]
I'm Victor from Mageplaza. I would like to answer to your issue.

- The above error occurred because the SocialLogin module is more specific than the Magento's Create extends file CreatePost file (http://prntscr.com/ph8cjp) but because Magento 2.3.3 has added two new components to the construct, the structural conflict causes the error.

- You can add new components to `**Mageplaza\SocialLogin\Controller\Popup\Create**` as follow  http://prntscr.com/ph8dio || http://prntscr.com/ph8dmp

**Comment by Userr017** [comment]
@Victor-Mageplaza Thanks it fix issue!

**Comment by an4rei** [comment]
#156 
Thanks !

**Comment by Victor-Mageplaza** [comment]
Since the issue has been resolved. I would like to close the topic here

**Comment by adamj88** [comment]
@Victor-Mageplaza would this update be able to be merged into master and released please? It's preventing upgrading to 2.3.3.

**Comment by BrM123** [comment]
I made your fix. The compilation was a success. Backend works but frontend does not work. Shows the following error:

{"0":"The \"form_additional_info\" is not a child of \"social-login-popup-create\". Resolve the issue and try again.","1":"<pre>#1 Magento\\Framework\\Data\\Structure->reorderToSibling() called at [vendor\/magento\/framework\/View\/Layout\/Data\/Structure.php:132]\n#2 Magento\\Framework\\View\\Layout\\Data\\Structure->reorderChildElement() called at [vendor\/magento\/framework\/View\/Layout\/GeneratorPool.php:176]\n#3 Magento\\Framework\\View\\Layout\\GeneratorPool->reorderElements() called at [vendor\/magento\/framework\/View\/Layout\/GeneratorPool.php:120]\n#4 Magento\\Framework\\View\\Layout\\GeneratorPool->buildStructure() called at [vendor\/magento\/framework\/View\/Layout\/GeneratorPool.php:79]\n#5 Magento\\Framework\\View\\Layout\\GeneratorPool->process() called at [vendor\/magento\/framework\/View\/Layout.php:343]\n#6 Magento\\Framework\\View\\Layout->generateElements() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:89]\n#7 Magento\\Framework\\View\\Layout\\Interceptor->generateElements() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:129]\n#8 Magento\\Framework\\View\\Layout\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Page\/Builder.php:55]\n#9 Magento\\Framework\\View\\Page\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:65]\n#10 Magento\\Framework\\View\\Layout\\Builder->build() called at [vendor\/magento\/framework\/View\/Layout.php:253]\n#11 Magento\\Framework\\View\\Layout->build() called at [vendor\/magento\/framework\/View\/Layout.php:875]\n#12 Magento\\Framework\\View\\Layout->getBlock() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:414]\n#13 Magento\\Framework\\View\\Layout\\Interceptor->getBlock() called at [vendor\/magento\/module-cms\/Helper\/Page.php:171]\n#14 Magento\\Cms\\Helper\\Page->prepareResultPage() called at [vendor\/magento\/module-cms\/Controller\/Index\/Index.php:74]\n#15 Magento\\Cms\\Controller\\Index\\Index->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#16 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#17 Magento\\Cms\\Controller\\Index\\Index\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#18 Magento\\Cms\\Controller\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#19 Magento\\Cms\\Controller\\Index\\Index\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Cms\/Controller\/Index\/Index\/Interceptor.php:26]\n#20 Magento\\Cms\\Controller\\Index\\Index\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#21 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#22 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#23 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#24 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php:94]\n#25 Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#26 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php:69]\n#27 Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#28 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#29 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#30 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:137]\n#31 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#32 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#33 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:40]\n<\/pre>","url":"\/","script_name":"\/index.php"}

> I'm Victor from Mageplaza. I would like to answer to your issue.
> 
> * The above error occurred because the SocialLogin module is more specific than the Magento's Create extends file CreatePost file (http://prntscr.com/ph8cjp) but because Magento 2.3.3 has added two new components to the construct, the structural conflict causes the error.
> * You can add new components to `**Mageplaza\SocialLogin\Controller\Popup\Create**` as follow  http://prntscr.com/ph8dio || http://prntscr.com/ph8dmp

**Comment by caribtraveler** [comment]
I made the changes as Victor's post showed.  However I am getting this error on compile.  I even set the permissions to 777 and I still get this error.

Class Magneto\Customer\Api\CustomerRepositoryInterface does not exist
Class Mageplaza\SocialLogin\Controller\Popup\Create\Interceptor generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only.

**Comment by caribtraveler** [comment]
....and after trying several more times setup:di:compile finally finished properly.  Not sure why or how?

**Comment by AigarsMurins** [comment]
@Victor-Mageplaza I do not understand why this issue is closed and why there is no patch? When is the fix added in to a new release?

**Comment by nicoaghe** [comment]
Hello @Victor-Mageplaza, 
Do you have any idea if this change will appear in the next update?
If yes, could you please tell me if you have a release date for the next update? 
I tried to create a controller to override the one in cause, but it appears an error from mageplaza_reports. The only way that works for me is if i change directly into the vendor files (which is not ideal, and i wouldn't want to do it that way).
Much apreciated, thank you!

**Comment by nix0x00** [comment]
Hey, I am also facing this issue on Magento 2.3.5-p1

What you told above already exist in `Create.php` but I am getting this issue.

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The "form_additional_info" is not a child of "social-login-popup-create". Resolve the issue and try again.

Exception #0 (Magento\Framework\Exception\LocalizedException): The "form_additional_info" is not a child of "social-login-popup-create". Resolve the issue and try again.
<pre>#1 Magento\Framework\Data\Structure->reorderToSibling() called at [vendor/magento/framework/View/Layout/Data/Structure.php:132]
```


I Installed via compsoer

**Comment by klispllc** [comment]
same issue. appreciate if any quick response. guess free extensions are a way to lure but end up in issues.

**Comment by klispllc** [comment]
same issue here. was suggested upgrading core. But that doesn't seem to resolve the issue. any more ideas ? Been stuck for last two weeks. 

thx
sri

**Comment by Victor-Mageplaza** [comment]
Hi,

Please go to **<your_Magento_root>/app/design/<your_theme>/** and find all **Mageplaza_SocialLogin** folders and delete them.
Or remove all the **social_login** from **pub/var/** folders 
Then run **setup and deploy** commands to complete fixing the issue.

Thank you!
Victor

**Comment by yaroslav-zenin** [comment]
> The "form_additional_info" is not a child of "social-login-popup-create". Resolve the issue and try again.
same exception
I use it with Mgs/claue theme

**Comment by ziyaindia** [comment]
> I'm Victor from Mageplaza. I would like to answer to your issue.
> 
> * The above error occurred because the SocialLogin module is more specific than the Magento's Create extends file CreatePost file (http://prntscr.com/ph8cjp) but because Magento 2.3.3 has added two new components to the construct, the structural conflict causes the error.
> * You can add new components to `**Mageplaza\SocialLogin\Controller\Popup\Create**` as follow  http://prntscr.com/ph8dio || http://prntscr.com/ph8dmp


**When I made these changes then I am getting following error during di:compile**

Class Magento\Customer\Api\Data\CustomerRepositoryInterfaceFactory does not exist                                                                                                                       
  Class Mageplaza\SocialLogin\Controller\Popup\Create\Interceptor generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- aft  
  er running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated  
   class object to the signature of the related construct method, only.
